## => Site Settings
##############################
text_skin: default 
highlight_theme: default 
url     : https://learn.piptrends.com
baseurl : /
title   : learn-pip-trends
tagline : Learn everything about Python
description: Learn everything about Python
author : Ashok Tankala
twitter:
  username: piptrends
  card: summary
logo: \assets\images\logo\Main-Logo.png
social:
  name: pip Trends
  links:
    - https://facebook.com/piptrends
    - https://www.instagram.com/piptrends
    - https://twitter.com/piptrends
    - https://www.youtube.com/@piptrends
    - https://linkedin.com/company/pip-trends
    - https://discord.gg/RdYEmSWP5t


## => Language and Timezone
##############################
lang: en
timezone: 


## => Author and Social
##############################
author:
  type      : person
  name      : Ashok Tankala
  url       : https://ashok.tanka.la/
  avatar    : # path or url of avatar image (square)
  bio       : I am an amazing person.
  email     : ashok@piptrends.com
  blog      : blog.piptrends.com
  youtube   : "@piptrends"
  facebook  : piptrends
  instagram : piptrends
  discord   : RdYEmSWP5t
  twitter   : piptrends
  linkedin  : pip-trends
  github    : tankala


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: tankala/learn-pip-trends
repository_tree: main


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: "h1,h2" 


## => Markdown Enhancements
##############################
## Mathjax
mathjax: true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: # false (default), true

## Chart
chart: # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
disqus_shortname: "learn-pip-trends"

## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Search
##############################
search:
  provider: "default" # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: google

  ## Google Analytics
  google:
    tracking_id : "G-714KN8K9WW"
    anonymize_ip: true

## => Link Preview
##############################
link-preview:
  title_max_characters: 64
  description_max_characters: 128

## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  - jekyll-url-metadata

#collections
collections:
  samplecode:
    output: true
  gettingstarted:
    output: true
  course:
    output: true
  blog:
    output: true
  relatedarticles:
    output: true
  faqs:
    output: true
  contribute:
    output: true
  pythontoolbox:
    output: true

defaults:
  - 
    scope:
      path: ""
      type: "gettingstarted"
    values:
      layout: article
      aside:
        toc: true
      comments: true
  - 
    scope:
      path: ""
      type: "samplecode"
    values:
      layout: article
      aside:
        toc: true
      comments: true
  -
    scope:
      path: ""
      type: "blog"
    values:
      layout: "article"
      comments: true
  -
    scope:
      path: ""
      type: "course"
    values:
      layout: "article"
      comments: true
  -
    scope:
      path: ""
      type: "relatedarticles"
    values:
      layout: "article"

  -
    scope:
      path: ""
      type: "faqs"
    values:
      layout: "article"

  -
    scope:
      path: ""
      type: "contribute"
    values:
      layout: "article"
  -
    scope:
      path: ""
      type: "pythontoolbox"
    values:
      layout: "article"